timeout: "1200s"
substitutions:
  _REGION: "asia-northeast3"
  _SERVICE_NAME: "energy-tycoon-backend"
  _REPO_NAME: "energy-tycoon-backend-repo"
options:
  substitution_option: ALLOW_LOOSE
  # Use regional user-owned bucket to satisfy BYOSA service account requirement
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
steps:
  - id: "build-and-push-image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail
        image_uri="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}"
        echo "Building ${image_uri}"
        docker build -t "${image_uri}" .
        docker push "${image_uri}"
        echo "${image_uri}" > /workspace/image_url.txt

  - id: "terraform-apply-cloud-run"
    name: "hashicorp/terraform:1.5.7"
    entrypoint: "bash"
    env:
      - "TF_LOG=ERROR"
      - "TF_VAR_image_tag=${SHORT_SHA}"
    secretEnv:
      - "TFVARS_CONTENT"
    args:
      - "-c"
      - |
        set -euo pipefail
        cd terraform
        export TF_VAR_image_url="$(cat /workspace/image_url.txt)"
        printf "%s" "${TFVARS_CONTENT}" > terraform.auto.tfvars
        terraform init -input=false
        terraform apply -auto-approve

availableSecrets:
  secretManager:
    - versionName: "projects/energytycoon/secrets/terraform-backend-tfvars/versions/latest"
      env: "TFVARS_CONTENT"
