version: "3"
services:
  backend:
    build: ./backend
    container_name: energy_backend
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: energy_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
